# Generated by Django 3.0.4 on 2020-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0003_auto_20200310_0541'),
        ] 

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_url',
            field=models.CharField(default='special offer', max_length=2083),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(default='5'),
            preserve_default=False,
        ),
    ]
