# Generated by Django 3.0.4 on 2020-03-18 22:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0004_auto_20200317_1639'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='offer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='discribtion',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
